In [248]:
print("Hello Pandas")

Hello Pandas

In [249]:
import numpy as np
import pandas as pd
import random

In [250]:
dict1 = {
    "name":["arjun","abinash","subhalaxmi","uttam ku murmu","biduyt ku. murmu","nabin murmu"],
    "marks":[90, 98, 91,89,88,92],
    "city":["sambalpur","balasore","baliapal","boudha","langleswar","bhubaneswar"]
}

In [251]:
df = pd.DataFrame(dict1)

In [252]:
df

               name  marks         city
0             arjun     90    sambalpur
1           abinash     98     balasore
2        subhalaxmi     91     baliapal
3    uttam ku murmu     89       boudha
4  biduyt ku. murmu     88   langleswar
5       nabin murmu     92  bhubaneswar

In [253]:
#export csv
df.to_csv('std1.csv')

In [254]:
df.to_csv("std_no_indx2.csv", index=False)

In [255]:
#start to show
df.head(2)

      name  marks       city
0    arjun     90  sambalpur
1  abinash     98   balasore

In [256]:
#ending to show 
df.tail(2)

               name  marks         city
4  biduyt ku. murmu     88   langleswar
5       nabin murmu     92  bhubaneswar

In [257]:
#memorical columan calculation
df.describe()

           marks
count   6.000000
mean   91.333333
std     3.559026
min    88.000000
25%    89.250000
50%    90.500000
75%    91.750000
max    98.000000

In [258]:
#READ The folder
#jaga is dataframe
jaga = pd.read_csv('jaga.csv')

In [259]:
jaga

   Unnamed: 0     Name  Balance Bank Name
0           0    Arjun     2100    Airtel
1           1  Abinash     2001       SBI
2           2    Uttam     1999       BOI
3           3    Nabin     1500       BOI
4           4   Biduyt     1200       SBI

In [260]:
#change the value and show the details
jaga['Balance']

0    2100
1    2001
2    1999
3    1500
4    1200
Name: Balance, dtype: int64

In [261]:
jaga['Balance'][0]

np.int64(2100)

In [262]:
#change
jaga['Balance'][0] = 2100

C:\Users\murmu\AppData\Local\Temp\ipykernel_5236\3439484613.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jaga['Balance'][0] = 2100

In [263]:
jaga

   Unnamed: 0     Name  Balance Bank Name
0           0    Arjun     2100    Airtel
1           1  Abinash     2001       SBI
2           2    Uttam     1999       BOI
3           3    Nabin     1500       BOI
4           4   Biduyt     1200       SBI

In [264]:
jaga.to_csv('jaga.csv')

In [265]:
jaga.index = ['first','second','third','four','five']

In [266]:
jaga

        Unnamed: 0     Name  Balance Bank Name
first            0    Arjun     2100    Airtel
second           1  Abinash     2001       SBI
third            2    Uttam     1999       BOI
four             3    Nabin     1500       BOI
five             4   Biduyt     1200       SBI

In [267]:
#series
ser = pd.Series(np.random.rand(20))

In [268]:
ser

0     0.240497
1     0.784333
2     0.485192
3     0.559691
4     0.013714
5     0.948700
6     0.555633
7     0.588475
8     0.192850
9     0.746121
10    0.213240
11    0.846952
12    0.386238
13    0.852882
14    0.688358
15    0.921544
16    0.292160
17    0.839074
18    0.848166
19    0.157487
dtype: float64

In [269]:
type(ser)

pandas.core.series.Series

In [270]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))

In [271]:
newdf

            0         1         2         3         4
0    0.982256  0.433480  0.612685  0.312137  0.594503
1    0.993033  0.567991  0.584520  0.365413  0.221660
2    0.835979  0.882954  0.826543  0.707181  0.505584
3    0.522537  0.880809  0.703221  0.514410  0.690154
4    0.997788  0.777014  0.386536  0.012773  0.851581
..        ...       ...       ...       ...       ...
329  0.138041  0.528196  0.941653  0.404945  0.888982
330  0.412827  0.130405  0.364311  0.286499  0.266651
331  0.073169  0.610325  0.622063  0.827701  0.399773
332  0.001076  0.186630  0.062864  0.590231  0.867576
333  0.730277  0.560398  0.706198  0.905592  0.853060

[334 rows x 5 columns]

In [272]:
newdf.head(5)

          0         1         2         3         4
0  0.982256  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154
4  0.997788  0.777014  0.386536  0.012773  0.851581

In [273]:
newdf.tail(5)

            0         1         2         3         4
329  0.138041  0.528196  0.941653  0.404945  0.888982
330  0.412827  0.130405  0.364311  0.286499  0.266651
331  0.073169  0.610325  0.622063  0.827701  0.399773
332  0.001076  0.186630  0.062864  0.590231  0.867576
333  0.730277  0.560398  0.706198  0.905592  0.853060

In [274]:
type(newdf)

pandas.core.frame.DataFrame

In [275]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.495118    0.470271    0.522811    0.487849    0.512984
std      0.306636    0.287350    0.280539    0.286385    0.289722
min      0.001076    0.007891    0.006908    0.000870    0.002563
25%      0.215409    0.205108    0.287141    0.240850    0.266945
50%      0.489557    0.456566    0.520748    0.499360    0.519532
75%      0.778555    0.727816    0.776330    0.733768    0.768295
max      0.997795    0.999072    0.996687    0.999628    0.997662

In [276]:
newdf.head(3)

          0         1         2         3         4
0  0.982256  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584

In [277]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [278]:
newdf[0][0] = "arjun"

C:\Users\murmu\AppData\Local\Temp\ipykernel_5236\3600279300.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = "arjun"
C:\Users\murmu\AppData\Local\Temp\ipykernel_5236\3600279300.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'arjun' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0] = "arjun"

In [279]:
newdf.head(4)

          0         1         2         3         4
0     arjun  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154

In [280]:
# DataType Change
newdf.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [281]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [282]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [283]:
#numpy convert
newdf.to_numpy()

array([['arjun', 0.43347982586953127, 0.6126851714656388,
        0.31213721283968365, 0.5945027891349096],
       [0.9930325048723221, 0.5679905130222346, 0.5845202712537361,
        0.3654126158185228, 0.22165981766305398],
       [0.8359792537435795, 0.8829540596045106, 0.8265426361378296,
        0.7071814556151145, 0.5055839251706775],
       ...,
       [0.07316941933117471, 0.6103246958353075, 0.6220628652110906,
        0.8277006671543881, 0.39977329449807686],
       [0.0010762529361362239, 0.1866304231729966, 0.0628638395815273,
        0.5902310214838439, 0.8675761156277326],
       [0.7302774220878463, 0.5603978979402436, 0.7061979447627418,
        0.9055924170471001, 0.853059899660402]],
      shape=(334, 5), dtype=object)

In [284]:
#Change the object
newdf[0][0] = 12

In [285]:
newdf.to_numpy()

array([[12, 0.43347982586953127, 0.6126851714656388, 0.31213721283968365,
        0.5945027891349096],
       [0.9930325048723221, 0.5679905130222346, 0.5845202712537361,
        0.3654126158185228, 0.22165981766305398],
       [0.8359792537435795, 0.8829540596045106, 0.8265426361378296,
        0.7071814556151145, 0.5055839251706775],
       ...,
       [0.07316941933117471, 0.6103246958353075, 0.6220628652110906,
        0.8277006671543881, 0.39977329449807686],
       [0.0010762529361362239, 0.1866304231729966, 0.0628638395815273,
        0.5902310214838439, 0.8675761156277326],
       [0.7302774220878463, 0.5603978979402436, 0.7061979447627418,
        0.9055924170471001, 0.853059899660402]],
      shape=(334, 5), dtype=object)

In [286]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,12,0.993033,0.835979,0.522537,0.997788,0.449218,0.548792,0.707631,0.085479,0.332301,...,0.345048,0.326304,0.123807,0.845041,0.824566,0.138041,0.412827,0.073169,0.001076,0.730277
1,0.43348,0.567991,0.882954,0.880809,0.777014,0.764363,0.86958,0.261921,0.323026,0.611536,...,0.164754,0.166685,0.558166,0.157467,0.979574,0.528196,0.130405,0.610325,0.18663,0.560398
2,0.612685,0.58452,0.826543,0.703221,0.386536,0.559819,0.613406,0.940676,0.474658,0.511795,...,0.868068,0.185249,0.853382,0.780275,0.727102,0.941653,0.364311,0.622063,0.062864,0.706198
3,0.312137,0.365413,0.707181,0.51441,0.012773,0.454165,0.371971,0.233308,0.104559,0.500318,...,0.467274,0.555928,0.733126,0.851996,0.082865,0.404945,0.286499,0.827701,0.590231,0.905592
4,0.594503,0.22166,0.505584,0.690154,0.851581,0.064768,0.215733,0.9931,0.903017,0.045154,...,0.632005,0.759629,0.353371,0.182727,0.45965,0.888982,0.266651,0.399773,0.867576,0.85306

In [287]:
newdf.head()

          0         1         2         3         4
0        12  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154
4  0.997788  0.777014  0.386536  0.012773  0.851581

In [288]:
newdf.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.730277  0.560398  0.706198  0.905592  0.853060
332  0.001076  0.186630  0.062864  0.590231  0.867576
331  0.073169  0.610325  0.622063  0.827701  0.399773
330  0.412827  0.130405  0.364311  0.286499  0.266651
329  0.138041  0.528196  0.941653  0.404945  0.888982
..        ...       ...       ...       ...       ...
4    0.997788  0.777014  0.386536  0.012773  0.851581
3    0.522537  0.880809  0.703221  0.514410  0.690154
2    0.835979  0.882954  0.826543  0.707181  0.505584
1    0.993033  0.567991  0.584520  0.365413  0.221660
0          12  0.433480  0.612685  0.312137  0.594503

[334 rows x 5 columns]

In [289]:
newdf.sort_index(axis=0)
#axis 0 = rows

            0         1         2         3         4
0          12  0.433480  0.612685  0.312137  0.594503
1    0.993033  0.567991  0.584520  0.365413  0.221660
2    0.835979  0.882954  0.826543  0.707181  0.505584
3    0.522537  0.880809  0.703221  0.514410  0.690154
4    0.997788  0.777014  0.386536  0.012773  0.851581
..        ...       ...       ...       ...       ...
329  0.138041  0.528196  0.941653  0.404945  0.888982
330  0.412827  0.130405  0.364311  0.286499  0.266651
331  0.073169  0.610325  0.622063  0.827701  0.399773
332  0.001076  0.186630  0.062864  0.590231  0.867576
333  0.730277  0.560398  0.706198  0.905592  0.853060

[334 rows x 5 columns]

In [290]:
newdf.sort_index(axis=1)

            0         1         2         3         4
0          12  0.433480  0.612685  0.312137  0.594503
1    0.993033  0.567991  0.584520  0.365413  0.221660
2    0.835979  0.882954  0.826543  0.707181  0.505584
3    0.522537  0.880809  0.703221  0.514410  0.690154
4    0.997788  0.777014  0.386536  0.012773  0.851581
..        ...       ...       ...       ...       ...
329  0.138041  0.528196  0.941653  0.404945  0.888982
330  0.412827  0.130405  0.364311  0.286499  0.266651
331  0.073169  0.610325  0.622063  0.827701  0.399773
332  0.001076  0.186630  0.062864  0.590231  0.867576
333  0.730277  0.560398  0.706198  0.905592  0.853060

[334 rows x 5 columns]

In [291]:
newdf.sort_index(axis=1, ascending=False)
#axis 1 meaning column

            4         3         2         1         0
0    0.594503  0.312137  0.612685  0.433480        12
1    0.221660  0.365413  0.584520  0.567991  0.993033
2    0.505584  0.707181  0.826543  0.882954  0.835979
3    0.690154  0.514410  0.703221  0.880809  0.522537
4    0.851581  0.012773  0.386536  0.777014  0.997788
..        ...       ...       ...       ...       ...
329  0.888982  0.404945  0.941653  0.528196  0.138041
330  0.266651  0.286499  0.364311  0.130405  0.412827
331  0.399773  0.827701  0.622063  0.610325  0.073169
332  0.867576  0.590231  0.062864  0.186630  0.001076
333  0.853060  0.905592  0.706198  0.560398  0.730277

[334 rows x 5 columns]

In [292]:
newdf.head()

          0         1         2         3         4
0        12  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154
4  0.997788  0.777014  0.386536  0.012773  0.851581

In [293]:
newdf[0]

0            12
1      0.993033
2      0.835979
3      0.522537
4      0.997788
         ...
329    0.138041
330    0.412827
331    0.073169
332    0.001076
333    0.730277
Name: 0, Length: 334, dtype: object

In [294]:
type(newdf[0])

pandas.core.series.Series

In [295]:
newdf2 = newdf

In [296]:
newdf2.head()

          0         1         2         3         4
0        12  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154
4  0.997788  0.777014  0.386536  0.012773  0.851581

In [297]:
newdf2[0][0] = 9877

C:\Users\murmu\AppData\Local\Temp\ipykernel_5236\1749725329.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0] = 9877

In [298]:
newdf

            0         1         2         3         4
0        9877  0.433480  0.612685  0.312137  0.594503
1    0.993033  0.567991  0.584520  0.365413  0.221660
2    0.835979  0.882954  0.826543  0.707181  0.505584
3    0.522537  0.880809  0.703221  0.514410  0.690154
4    0.997788  0.777014  0.386536  0.012773  0.851581
..        ...       ...       ...       ...       ...
329  0.138041  0.528196  0.941653  0.404945  0.888982
330  0.412827  0.130405  0.364311  0.286499  0.266651
331  0.073169  0.610325  0.622063  0.827701  0.399773
332  0.001076  0.186630  0.062864  0.590231  0.867576
333  0.730277  0.560398  0.706198  0.905592  0.853060

[334 rows x 5 columns]

In [299]:
#copy file
newdf2 = newdf.copy()

In [300]:
newdf2[0][0] = 112

C:\Users\murmu\AppData\Local\Temp\ipykernel_5236\1948515364.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 112
C:\Users\murmu\AppData\Local\Temp\ipykernel_5236\1948515364.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0] = 112

In [301]:
newdf.head()

          0         1         2         3         4
0      9877  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154
4  0.997788  0.777014  0.386536  0.012773  0.851581

In [302]:
newdf2.head()

          0         1         2         3         4
0       112  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154
4  0.997788  0.777014  0.386536  0.012773  0.851581

In [303]:
newdf.loc[0,0] = 54

In [304]:
newdf.head(2)

          0         1         2         3         4
0        54  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660

In [305]:
newdf.columns = list("ABCDE")

In [306]:
newdf.head(4)

          A         B         C         D         E
0        54  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154

In [307]:
newdf.loc[0,'A'] = 234

In [308]:
newdf.head(3)

          A         B         C         D         E
0       234  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584

In [309]:
newdf.loc[0,0] = 20

In [310]:
newdf.head()

          A         B         C         D         E     0
0       234  0.433480  0.612685  0.312137  0.594503  20.0
1  0.993033  0.567991  0.584520  0.365413  0.221660   NaN
2  0.835979  0.882954  0.826543  0.707181  0.505584   NaN
3  0.522537  0.880809  0.703221  0.514410  0.690154   NaN
4  0.997788  0.777014  0.386536  0.012773  0.851581   NaN

In [311]:
#drop column
newdf = newdf.drop(0, axis=1)

In [312]:
#Specific data show
data_show = newdf.loc[[1,2],['C','D']]
data_show.to_csv("data_show.csv")

In [313]:
newdf.head()

          A         B         C         D         E
0       234  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154
4  0.997788  0.777014  0.386536  0.012773  0.851581

In [314]:
newdf.loc[:,['C','D']].head(10)

          C         D
0  0.612685  0.312137
1  0.584520  0.365413
2  0.826543  0.707181
3  0.703221  0.514410
4  0.386536  0.012773
5  0.559819  0.454165
6  0.613406  0.371971
7  0.940676  0.233308
8  0.474658  0.104559
9  0.511795  0.500318

In [315]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584

In [316]:
newdf.loc[(newdf['A']<0.3)]

            A         B         C         D         E
8    0.085479  0.323026  0.474658  0.104559  0.903017
13    0.07563  0.194096  0.523712  0.476754  0.454296
18   0.234778  0.990981  0.725130  0.708831  0.258546
21   0.070462  0.014878  0.456511  0.256334  0.472876
24   0.087584  0.007891  0.844025  0.972126  0.714128
..        ...       ...       ...       ...       ...
323  0.125946  0.982824  0.085207  0.614822  0.193744
326  0.123807  0.558166  0.853382  0.733126  0.353371
329  0.138041  0.528196  0.941653  0.404945  0.888982
331  0.073169  0.610325  0.622063  0.827701  0.399773
332  0.001076  0.186630  0.062864  0.590231  0.867576

[102 rows x 5 columns]

In [317]:
newdf.loc[(newdf['A']<0.3) & (newdf['C'] > 0.1)]

            A         B         C         D         E
8    0.085479  0.323026  0.474658  0.104559  0.903017
13    0.07563  0.194096  0.523712  0.476754  0.454296
18   0.234778  0.990981  0.725130  0.708831  0.258546
21   0.070462  0.014878  0.456511  0.256334  0.472876
24   0.087584  0.007891  0.844025  0.972126  0.714128
..        ...       ...       ...       ...       ...
318  0.287501  0.289244  0.718545  0.050928  0.560302
320  0.010523  0.326171  0.362948  0.811449  0.868225
326  0.123807  0.558166  0.853382  0.733126  0.353371
329  0.138041  0.528196  0.941653  0.404945  0.888982
331  0.073169  0.610325  0.622063  0.827701  0.399773

[89 rows x 5 columns]

In [318]:
#ilock 
newdf.head(4)

          A         B         C         D         E
0       234  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154

In [319]:
newdf.iloc[0,4]

np.float64(0.5945027891349096)

In [320]:
newdf.iloc[0,3]

np.float64(0.31213721283968365)

In [321]:
newdf.iloc[1,2]

np.float64(0.5845202712537361)

In [322]:
newdf.head()

          A         B         C         D         E
0       234  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154
4  0.997788  0.777014  0.386536  0.012773  0.851581

In [323]:
newdf.iloc[[1,3],[2,4]]

          C         E
1  0.584520  0.221660
3  0.703221  0.690154

In [324]:
newdf.head(3)

          A         B         C         D         E
0       234  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584

In [325]:
#row drop
newdf.drop([0])

            A         B         C         D         E
1    0.993033  0.567991  0.584520  0.365413  0.221660
2    0.835979  0.882954  0.826543  0.707181  0.505584
3    0.522537  0.880809  0.703221  0.514410  0.690154
4    0.997788  0.777014  0.386536  0.012773  0.851581
5    0.449218  0.764363  0.559819  0.454165  0.064768
..        ...       ...       ...       ...       ...
329  0.138041  0.528196  0.941653  0.404945  0.888982
330  0.412827  0.130405  0.364311  0.286499  0.266651
331  0.073169  0.610325  0.622063  0.827701  0.399773
332  0.001076  0.186630  0.062864  0.590231  0.867576
333  0.730277  0.560398  0.706198  0.905592  0.853060

[333 rows x 5 columns]

In [326]:
#column drop
newdf.drop(['C'], axis=1)

            A         B         D         E
0         234  0.433480  0.312137  0.594503
1    0.993033  0.567991  0.365413  0.221660
2    0.835979  0.882954  0.707181  0.505584
3    0.522537  0.880809  0.514410  0.690154
4    0.997788  0.777014  0.012773  0.851581
..        ...       ...       ...       ...
329  0.138041  0.528196  0.404945  0.888982
330  0.412827  0.130405  0.286499  0.266651
331  0.073169  0.610325  0.827701  0.399773
332  0.001076  0.186630  0.590231  0.867576
333  0.730277  0.560398  0.905592  0.853060

[334 rows x 4 columns]

In [327]:
#column drop
newdf.drop(['C','A'], axis=1)

            B         D         E
0    0.433480  0.312137  0.594503
1    0.567991  0.365413  0.221660
2    0.882954  0.707181  0.505584
3    0.880809  0.514410  0.690154
4    0.777014  0.012773  0.851581
..        ...       ...       ...
329  0.528196  0.404945  0.888982
330  0.130405  0.286499  0.266651
331  0.610325  0.827701  0.399773
332  0.186630  0.590231  0.867576
333  0.560398  0.905592  0.853060

[334 rows x 3 columns]

In [328]:
newdf.head()

          A         B         C         D         E
0       234  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154
4  0.997788  0.777014  0.386536  0.012773  0.851581

In [329]:
newdf.loc[0,0] = 12

In [330]:
newdf[1] = 34

In [331]:
newdf

            A         B         C         D         E     0   1
0         234  0.433480  0.612685  0.312137  0.594503  12.0  34
1    0.993033  0.567991  0.584520  0.365413  0.221660   NaN  34
2    0.835979  0.882954  0.826543  0.707181  0.505584   NaN  34
3    0.522537  0.880809  0.703221  0.514410  0.690154   NaN  34
4    0.997788  0.777014  0.386536  0.012773  0.851581   NaN  34
..        ...       ...       ...       ...       ...   ...  ..
329  0.138041  0.528196  0.941653  0.404945  0.888982   NaN  34
330  0.412827  0.130405  0.364311  0.286499  0.266651   NaN  34
331  0.073169  0.610325  0.622063  0.827701  0.399773   NaN  34
332  0.001076  0.186630  0.062864  0.590231  0.867576   NaN  34
333  0.730277  0.560398  0.706198  0.905592  0.853060   NaN  34

[334 rows x 7 columns]

In [332]:
newdf.drop([0], axis=1, inplace=True)

In [333]:
newdf.head()

          A         B         C         D         E   1
0       234  0.433480  0.612685  0.312137  0.594503  34
1  0.993033  0.567991  0.584520  0.365413  0.221660  34
2  0.835979  0.882954  0.826543  0.707181  0.505584  34
3  0.522537  0.880809  0.703221  0.514410  0.690154  34
4  0.997788  0.777014  0.386536  0.012773  0.851581  34

In [334]:
newdf.drop(columns=[1], inplace=True)

In [335]:
newdf.head()

          A         B         C         D         E
0       234  0.433480  0.612685  0.312137  0.594503
1  0.993033  0.567991  0.584520  0.365413  0.221660
2  0.835979  0.882954  0.826543  0.707181  0.505584
3  0.522537  0.880809  0.703221  0.514410  0.690154
4  0.997788  0.777014  0.386536  0.012773  0.851581

In [336]:
newdf.drop([(0,1)], axis=1, inplace=True)

KeyError: '[(0, 1)] not found in axis'

In [ ]:
newdf.head()

In [ ]:
newdf.reset_index()

In [ ]:
newdf.reset_index(drop=True, inplace = True)

In [ ]:
newdf.head()

In [ ]:
newdf['B'] = None

In [ ]:
newdf['B'].isnull()

In [ ]:
newdf

In [ ]:
newdf.loc[:,['B']] = 34

In [ ]:
newdf

In [ ]:
#new dataFrame with new function
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']
       }

In [ ]:
data

In [ ]:
datadf = pd.DataFrame(data)

In [ ]:
datadf

In [ ]:
d = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, 7, 8],
    'C': [9, 10, 11, np.nan],
    'D': [3, np.nan, np.nan, np.nan],
    'E': [np.nan, np.nan, np.nan, np.nan]
})

In [ ]:
d

In [ ]:
d.dropna()

In [ ]:
d

In [ ]:
d.dropna(how = "all", axis = 1)

In [ ]:
#Drop Duplicate value remove

dup = pd.DataFrame({
    'A': [1, "jaga", "jaga", 4],
    'B': [5, np.nan,"jaga", 8],
    'C': [9, 10, "jaga", np.nan],
    'D': [3, np.nan, np.nan, np.nan],
    'E': [np.nan, np.nan, np.nan, np.nan]
})

In [ ]:
dup

In [ ]:
dup.drop_duplicates(subset=['A'])

In [ ]:
dup.drop_duplicates(subset=['A'],keep='first')

In [ ]:
dup.drop_duplicates(subset=['A'],keep='last')

In [ ]:
dup.drop_duplicates(subset=['A'],keep=False)

In [ ]:
dup.shape

In [ ]:
dup.info()

In [ ]:
datadf.info()

In [ ]:
jjaga = pd.read_excel('jaga.xlsx', sheet_name = 'Sheet1')

In [ ]:
jjaga

In [ ]:
jjaga = pd.read_excel('jaga.xlsx', sheet_name = 'Sheet2')

In [ ]:
jjaga

In [ ]:
jjaga.iloc[0,0] = 123

In [ ]:
jjaga

In [ ]:
jjaga.to_excel('jaga.xlsx', sheet_name='Sheet2')